### ISSUE TITLE
Catalog API

### ISSUE THREAD

**Issue by S0c5** [virto-network/virto-apis#1]
Hey we need to build a catalog API that allow to SMB'S to:

- [x] Create a product
- [ ] Create bulk variations for a specific product
- [x] List products preview given a SMB wallet address and optional query parameters

**Comment by olanod** [comment]
This API would be part of the **Merchant API** since it's related to all the basic activities of a merchant, initially it's just a matter of name-spacing the endpoints like `GET /merchant/catalog` or `PUT /merchant/catalog/ABV123`

**Comment by JorgeVV** [comment]
Nice job with the initial implementation @S0c5 PR #2.

There are some fields that are still missing.
- `warranty` in units of time.
- Package dimensions: width, height, length, weight.
- Estimated delivery time.
- Minimum amount of units to trigger stock alert.
- General category-related attributes. For `FashionAndAccesories` category, these would be `brand`, `material`, etc.
- Variation attributes. For `FashionAndAccesories` category, these would be `color`, `size`, etc.

**Comment by S0c5** [comment]
# Changes


## `warranty in units of time:`

added a new field to ItemVariation which is wrrany_time, it has the next structure: 
```
{
 type: 'ItemVariation',
 data: {
    warranty_time_seconds: 10000
    warranty_time_type: Fixed
    ...
  }
}
```

## `Package dimensions: width, height, length, weight.`

added new entity `ItemDelivery` with attributes:

- `item_id`
- `type`:  'trasnportation' | 'own_delivery' 
// for transportation & own_delivery
- `width_mm`: number 
- `height_mm`: number
- `length_mm`: number
- `weight_grams`: number

// further, we can enable take_in or Pick-up and then people can go to the merchant address directly


## `Estimated delivery time: `

added new fields to modifications and variations


```
{
 type: 'ItemVariation',
 data: {
    processing_time_seconds: 10000
    processing_time_type: Fixed
    ...
  },
   type: 'ItemModification',
   data: {
      processing_time_seconds: 10000
      processing_time_type: Fixed
      ...
    },
}
```


## `Minimum amount of units to trigger a stock alert.`
```
I propose to delete that meanwhile in the front-end and create a separate ticket to think about how inventory should work. 
```

new ItemInventory if present means that inventory is enabled and allows configurations related, including stock units alert

ItemInventory {
// flatted 
- stock_config: Optional<{
  minimium_amount: i32
}> 
}


## `General category-related attributes. For FashionAndAccesories category, these would be brand, material, etc`

added an extra field to ItemVariation which is ExtraAttributes

added a new field to ItemVariation which is wrrany_time, it has the next structure: 
```
{
 type: 'ItemVariation',
 data: {
    extra_attributes: null | {
      [name],  [value string],
    }
    ...
  }
}
```



##  `Variation attributes. For FashionAndAccesories category, these would be color, size, etc`

I propose the inclusion of ItemControl which allow us to define the front-end behavior related to how to localize the variations, given some attributes
it could be type: 

```
// example to lookup with size and color the variation id
// size:S and color:blue look for id:4 in the matrix given that size:S is in the index 0 of x_options and color:blue is at index 1 n y_options then the matrix[0][1] = 4
{
  type: 'Matrix2d' 
   // matrix of ids
   data: {
      matriz: [
         [1,2,3],
         [None,4,None]
      ],
      x_name: "size",
      x_options: ["s", "m"],
      y_name: "color",
      y_options: ["red", "blue", "orange"],
   },
},
// example to lookup with size and color the variation id
// size:S, color:blue, extra:"b"  look for id:5 in the matrix given that size:S is in the index 0 of x_options and color:blue is at index 1 and extra:b: "1" the matrix[0][1][1] = 5
{
  type: 'Matrix3d' 
   // matrix of ids
   data: {
      matriz: [
         [ 
           [1,2,3],
           [4,5,6] ,
           [7,8,9]
         ],
      ],
      x_name: "size",
      x_options: ["s", "m"],
      y_name: "color",
      y_options: ["red", "blue", "orange"],
      z_name: "extra",
      z_options: ["a", "b", "c"],
   },
}
```
